packages:
  # all packages
  - 'packages/*'
  # website
  - 'site'
overrides:
  '@monaco-editor/loader': 1.5.0

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  core-js-pure: true
  esbuild: true
  gl: true
