packages:
  # all packages
  - 'packages/*'
  # website
  - 'site'
allowBuilds:
  '@parcel/watcher': set this to true or false
  '@swc/core': set this to true or false
  core-js: set this to true or false
  core-js-pure: set this to true or false
  esbuild: set this to true or false
  gl: set this to true or false
